language: go

go:
  - 1.5.2
  - 1.6rc2
  - tip

matrix:
  allow_failures:
    - go: tip

sudo: false

os:
  - linux
  - osx

# ssh_known_hosts is broken on OS X, run ssh-keyscan manually instead
# See https://github.com/travis-ci/travis-ci/issues/5596
# addons:
#   ssh_known_hosts:
#     - bitbucket.org
before_install:
  - ssh-keyscan -t rsa -T 30 -H bitbucket.org | tee -a $HOME/.ssh/known_hosts

env:
  global:
    - GO15VENDOREXPERIMENT="1"

install:
  - true

script:
  - go test -v ./...
