language: go

go:
  - 1.5.2
  - 1.6rc2
  - tip

sudo: false

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/dupes/openssh; fi

addons:
  ssh_known_hosts:
    - bitbucket.org

env:
  global:
    - GO15VENDOREXPERIMENT="1"

install:
  - true

script:
  - go test -v ./...
